ror_app/config/routes.rb
Rails.application.routes.draw do

  resources :billings do
    member do
      get :product_details
    end
  end
  resources :customers do
    member do
      post :send_email
    end
  end
  resources :products
  resources :denominations

  root 'billings#index'
end

ror_app/app/models/product.rb
class Product < ApplicationRecord

  ##########  Validation  ###############

  validates :name, presence: true, uniqueness: true
  validates_numericality_of :unit_price, greater_than: 0
  validates_numericality_of :tax_percentage, greater_than: 0
  validate :whether_it_has_child

  def whether_it_has_child
    if self.product_details.size > 0
      errors.add(:product, " used in existing customers bill, so can't update")
    end
  end

  ###########  Association ##############

  has_many :product_details, :dependent => :restrict_with_error
  has_many :billings, through:  :product_details
end

ror_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :find_product, only: [:edit, :update, :destroy]
  after_action :clear_flash, only: [:create, :update, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @product = Product.new(get_products)
    flash[:notice] = "Product created successfully!!!"
    respond_to do |format|
      if @product.save
        format.html
        format.js
      else
        format.html
        format.js
      end
    end
  end

  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    flash[:notice] = "Product updated successfully!!!"
    respond_to do |format|
      if @product.update(get_products)
        format.js
        format.html
      else
        format.js
        format.html
      end
    end
  end

  def destroy
    @product.destroy
    if @product.errors.any?
      flash[:notice] = 'Cannot delete the product, since it is added in some bills'
    else
      flash[:notice] = 'Product deleted successfully!!!'
    end
    respond_to do |format|
      format.js
      format.html
    end
  end
  private
    def get_products
      params.require(:product).permit(:name, :unit_price, :tax_percentage)
    end

    def find_product
      @product = Product.find(params[:id])
    end

    def clear_flash
      flash.discard
    end
end

ror_app/app/helpers/products_helper.rb
module ProductsHelper
end

ror_app/app/views/products/_errors.html.erb
<div id="errors">
  <h1><%= products.errors.count %> errors occured</h1>
  <ul>
    <% products.errors.full_messages.each do |message| %>
      <li>
        <%= message %><br/>
      </li>
    <% end %>
  </ul>
</div>

ror_app/app/views/products/_form.html.erb
<%= form_for products, remote: true do |product| %>


    <div id="error_division">
    </div>


    <div class="form-group row">
      <label for="name" class="col-md-4">Product Name</label>
      <div class="col-md-8">
        <%= product.text_field :name, class: 'form-control col-md-8', placeholder: 'Enter unique name', autocomplete: 'off' %>
      </div>
    </div>

    <div class="form-group row">
      <label for="unit_price" class="col-md-4">Unit Price</label>
      <div class="col-md-8">
        <%= product.text_field :unit_price, class: 'form-control col-md-8', placeholder: 'Enter Unit price', autocomplete: 'off' %>
      </div>
    </div>

    <div class="form-group row">
      <label for="tax_percentage" class="col-md-4">Tax percentage</label>
      <div class="col-md-8">
        <%= product.text_field :tax_percentage, class: 'form-control col-md-8', placeholder: 'Enter tax% for product', autocomplete: 'off' %>
      </div>
    </div>

  <br/>
  <%= product.submit 'Submit', class: 'btn btn-success' %>
<% end %>

ror_app/app/views/products/_product_row.html.erb
<td><%= product.name %></td>
<td><%= product.unit_price %></td>
<td><%= product.tax_percentage %></td>
<td><%= link_to 'Update', edit_product_path(product), class: 'btn btn-primary', remote: true %></td>
<td><%= link_to 'Delete', product_path(product) ,method: :delete, data: { confirm: 'Are you sure to delete the product?'}, class: 'btn btn-danger', id: product.id, remote: true %></td>

ror_app/app/views/products/create.js.erb
<% if @product.errors.any? %>
  $('#error_division').html('<%= j render 'errors',products: @product %>');
<% else %>
  $('#products').modal('hide');
  $('#product_table').append('<tr id="product_<%= @product.id %>">\n'+'<%= j render 'products/product_row', product: @product %>\n'+'</tr>');
  $('#flash_message').html('<div class="alert alert-success" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>

ror_app/app/views/products/destroy.js.erb
var product = document.getElementById("<%= @product.id %>");
<% unless @product.errors.any? %>
  product.parentNode.parentNode.remove();
<% end %>
$('#flash_message').html('<div class="alert alert-danger" id="message_shower"><%= flash[:notice] %></div>');
setTimeout(remove_flash_message,3000);

function remove_flash_message(){
    $('#message_shower').remove();
}

ror_app/app/views/products/edit.html.erb
<%= render 'form', products: update_product %>

ror_app/app/views/products/edit.js.erb
$('#products').modal();
$('#title').html('Update product');
$('#form').html('<%= j render 'form', products: @product %>')

ror_app/app/views/products/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">


  <a class="navbar-brand" href="/customers">Bill List</a>
  <a class="navbar-brand" href="/denominations">Denominations</a>
  <a class="navbar-brand" href="/billings">New Bill</a>

</nav>
<div id="flash_message"></div>
<% if flash[:alert] %>
  <div class="alert alert-warning">
    <%= flash[:alert] %>
  </div>
<% end %>
<h1>Available products in the shop</h1>
<table class="table table-striped">
  <thead align="center">
    <tr>
      <th>Product Name</th>
      <th>Unit price</th>
      <th>Tax percentage</th>
      <th>Edit</th>
      <th>Remove</th>
    </tr>
  </thead>
  <tbody align="center" id="product_table">
    <% @products.each do |product| %>
      <tr id="product_<%= product.id %>">
        <%= render 'products/product_row', product: product %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add new product', new_product_path, class: 'btn btn-success',  remote: true, 'data-toggle' =>  "modal", 'data-target' => '#new_product' %>
<div class="modal fade" id="products" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="title"></h1>
      </div>
      <div class="modal-body">
        <div id="form"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

ror_app/app/views/products/new.html.erb
<%= render 'form', products: @product %>

ror_app/app/views/products/new.js.erb
$("#products").modal();
$('#title').html('New product');
$('#form').html('<%= j render 'form', products: @product %>')

ror_app/app/views/products/update.js.erb
<% if @product.errors.any? %>
  $('#error_division').html('<%= j render 'errors', products: @product %>');
<% else %>

  $('#products').modal('hide');
  $('#product_<%= @product.id %>').html('<%= j render 'products/product_row', product: @product %>');
  $('#flash_message').html('<div class="alert alert-info" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>