ror_app/config/routes.rb
Rails.application.routes.draw do

  resources :billings do
    member do
      get :product_details
    end
  end
  resources :customers do
    member do
      post :send_email
    end
  end
  resources :products
  resources :denominations

  root 'billings#index'
end

ror_app/app/models/denomination.rb
class Denomination < ApplicationRecord

  ############  Validation  ################

  validates :rupees, uniqueness: true, numericality: { greater_than:  0 }
  validates_numericality_of :count, greater_than_or_equal_to: 0
end

ror_app/app/controllers/denominations_controller.rb
class DenominationsController < ApplicationController

  before_action :get_denomination_id, only: [:edit, :update, :destroy]
  after_action :clear_flash, only: [:create, :update, :destroy]

  def index
    @denominations = Denomination.all.order(rupees: :desc)
  end

  def new
    @denomination = Denomination.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @denomination = Denomination.new(get_denomination)
    flash[:notice] = "Denomination created successfully!!!"
    respond_to do |format|
      if @denomination.save
        format.js
        format.html
      else
        format.js
        format.html
      end
    end

  end

  def edit
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    flash[:notice] = "Denomination updated successfully!!!"
    respond_to do |format|
      if @denomination.update(get_denomination)
        format.js
        format.html
      else
        format.js
        format.html
      end
    end
  end

  def destroy
    @denomination.destroy
    flash[:notice] = "Denomination deleted successfully!!!"
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
    def get_denomination
      params.require(:denomination).permit(:rupees,:count)
    end

    def get_denomination_id
      @denomination = Denomination.find(params[:id])
    end

    def clear_flash
      flash.discard
    end
end

ror_app/app/helpers/denominations_helper.rb
module DenominationsHelper
end

ror_app/app/views/denominations/_denomination_row.html.erb
<td><%= denomination.rupees %></td>
<td><%= denomination.count %></td>
<td><%= link_to 'Update', edit_denomination_path(denomination), class: 'btn btn-primary', remote: true %></td>
<td><%= link_to 'Delete', denomination_path(denomination), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', id: denomination.id, remote: true %></td>

ror_app/app/views/denominations/_errors.html.erb
<div id="errors">
  <h1><%= denomination.errors.count %> errors occured</h1>
  <ul>
    <% denomination.errors.full_messages.each do |message| %>
      <li>
        <%= message %><br/>
      </li>
    <% end %>
  </ul>
</div>

ror_app/app/views/denominations/_form.html.erb
<%= form_for denomination, remote: true do |denominations| %>

  <div id="error_division"></div>


  <div class="form-group row">
    <label for="rupees" class="col-md-2">Rupees</label>
    <div class="col-md-8">
      <%= denominations.text_field :rupees, autocomplete: 'off', class: 'form-control col-md-8' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="count" class="col-md-2">Count</label>
    <div class="col-md-8">
      <%= denominations.text_field :count, autocomplete: 'off', class: 'form-control col-md-8' %>
    </div>
  </div>

  <%= denominations.submit 'Submit', class: 'bt btn-success' %>
<% end %>
<br/>

ror_app/app/views/denominations/create.js.erb
<% if @denomination.errors.any? %>
  $('#error_division').html('<%= j render 'errors', denomination: @denomination %>')
<% else %>
  $('#denominations').modal('hide');
  $('#denomination_table').append('<tr id="denomination_<%= @denomination.id %>">\n'+'<%= j render 'denominations/denomination_row', denomination: @denomination %>\n'+'</tr>');
  $('#flash_message').html('<div class="alert alert-success" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>

ror_app/app/views/denominations/destroy.js.erb
var denomination = document.getElementById("<%= @denomination.id %>");
denomination.parentNode.parentNode.remove();
$('#flash_message').html('<div class="alert alert-danger" id="message_shower"><%= flash[:notice] %></div>');
setTimeout(remove_flash_message,3000);

function remove_flash_message(){
    $('#message_shower').remove();
}

ror_app/app/views/denominations/edit.html.erb
<h1>Update Denomination</h1><br/>
<%= render 'form', denomination: @denomination %>

ror_app/app/views/denominations/edit.js.erb
$('#denominations').modal();
$('#title').html('Update denomination');
$('#form').html('<%= j render 'form', denomination: @denomination %>')

ror_app/app/views/denominations/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">


  <a class="navbar-brand" href="/customers">Bill List</a>
  <a class="navbar-brand" href="/billings">New Bill</a>
  <a class="navbar-brand" href="/products">Products</a>

</nav>
<div id="flash_message"></div>

<h1>In denominations</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Rupees</th>
      <th>Count</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody id="denomination_table">
    <% @denominations.each do |denomination| %>
      <tr id="denomination_<%= denomination.id %>">
        <%= render 'denominations/denomination_row', denomination: denomination %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Denomination', new_denomination_path, class: 'btn btn-success', remote: true %>
<div class="modal fade" id="denominations" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title" id="title"></h1>
      </div>
      <div class="modal-body">
        <div id="form"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

ror_app/app/views/denominations/new.html.erb
<h1>New Denomination</h1><br/>
<%= render 'form', denomination: @denomination %>

ror_app/app/views/denominations/new.js.erb
$('#denominations').modal();
$('#title').html('New denomination');
$('#form').html('<%= j render 'form', denomination: @denomination %>')

ror_app/app/views/denominations/update.js.erb
<% if @denomination.errors.any? %>
  $('#error_division').html('<%= j render 'errors', denomination: @denomination %>');
<% else %>
  $('#denominations').modal('hide');
  $('#denomination_<%= @denomination.id %>').html('<%= j render 'denominations/denomination_row', denomination: @denomination %>');
  $('#flash_message').html('<div class="alert alert-info" id="message_shower"><%= flash[:notice] %></div>');
  setTimeout(remove_flash_message,3000);

  function remove_flash_message(){
      $('#message_shower').remove();
  }
<% end %>