ror_app/config/routes.rb
Rails.application.routes.draw do

  resources :billings do
    member do
      get :product_details
    end
  end
  resources :customers do
    member do
      post :send_email
    end
  end
  resources :products
  resources :denominations

  root 'billings#index'
end

ror_app/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include Pagy::Backend

  before_action :get_billing_by_id, except: :index

  def index
    @pagy, @customers = params[:email].present? ? pagy(Billing.where(email: params[:email]).order(created_at: 'DESC'), items: 10) : pagy(Billing.all.order(created_at: 'DESC'), items: 10)
  end

  def show
    @product_details  = @billing.product_details.includes(:product)
  end

  def send_email
    PurchaseMailer.show_details(@billing).deliver

    redirect_to customer_path(@billing), notice: "Email sent successfully!!!"
  end

  private
    def get_billing_by_id
      @billing = Billing.find(params[:id])
    end
end

ror_app/app/helpers/customers_helper.rb
module CustomersHelper
end

ror_app/app/views/customers/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">

  <a class="navbar-brand" href="/denominations">Denominations</a>
  <a class="navbar-brand" href="/billings">New Bill</a>
  <a class="navbar-brand" href="/products">Products</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="pull-right">
    <form class="form-inline ml-auto" action="/customers" method="get">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="email" autocomplete="off">
      </div>
      <button class="btn btn-light" type="submit">Search</button>
      <i class="fas fa-search text-white ml-3" aria-hidden="true"></i>
    </form>
    </div>
  </div>

</nav>
<h1>DETAILS OF A CUSTOMERS</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Paid amount</th>
      <th>Purchased Date</th>
      <th>Purchased Time</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.email, customer_path(customer) %><br/></td>
        <td><%= customer.amount %></td>
        <td><%= customer.created_at.to_date %></td>
        <td><%= customer.created_at.strftime("%I:%M %p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-inline">
  <%= render template: "shared/paginator", locals: { pagy: @pagy }%>
</div>

ror_app/app/views/customers/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">

  <a class="navbar-brand" href="/customers">Bill List</a>
  <a class="navbar-brand" href="/denominations">Denominations</a>
  <a class="navbar-brand" href="/billings">New Bill</a>
  <a class="navbar-brand" href="/products">Products</a>

</nav>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="row">
  <div class="col-md-1" style="background: powderblue">

  </div>
  <div class="col-md-10">
      <h1>Billing System</h1>

    <br/>
    <p><b>Customer Email</b></p>
    <p><%= @billing.email %></p>
    <br/>

    <h1>Bill Section<%= link_to 'Send email', send_email_customer_path, method: :post, class: 'btn btn-success', style: 'float: right' %></h1>
    <table class="table table-striped">
      <thead align="center">
      <tr>
        <th>Product name</th>
        <th>Unit Price</th>
        <th>Quantity</th>
        <th>Purchased Price</th>
        <th>Tax % for item</th>
        <th>Tax payable for item</th>
        <th>Total price of the item</th>
      </tr>
      </thead>
      <tbody align="center">
      <% @product_details.each do |product_detail| %>
        <tr>
          <td><%= product_detail.product.name %></td>
          <td><%= '%.2f' % product_detail.product.unit_price %></td>
          <td><%= product_detail.quantity %></td>
          <td><%= '%.2f' % product_detail.purchased_price %></td>
          <td><%= product_detail.product.tax_percentage %></td>
          <td><%= '%.2f' % product_detail.tax_payable_for_item %></td>
          <td><%= '%.2f' % product_detail.total_price_of_item %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br/>
    <h1>Balance Denominations</h1>
    <% @billing.balance.each do |rupees,count| %>
      <div class="form-group row">
        <div class="col-md-1">
          <%= rupees %>
        </div>
        <div class="col-md-2">
          <%= count %>
        </div>
      </div>

    <% end %>

  </div>
  <div class="col-md-1" style="background: powderblue">

  </div>
</div>

  <div class="row">
    <div class="col-md-1" style="background: powderblue">

    </div>
    <div class="col-md-9" align="right" style="background: #DADADA">
      <br/>
      <p><b>Total price without tax:</b></p>
      <p><b>Total tax payable:</b></p>
      <p><b>Net prize of the purchased item:</b></p>
      <p><b>Rounded down value of the purchased items net price:</b></p>
      <p><b>Balance payable to the customer:</b></p>
    </div>
    <div class="col-md-1" style="background: #DADADA">
      <br/>

      <p align="right"><%= '%.2f' % @billing.without_tax %></p>
      <p align="right"><%= '%.2f' % @billing.tax_price %></p>
      <p align="right"><%= '%.2f' % (@billing.without_tax + @billing.tax_price) %></p>
      <p align="right"><%= '%.2f' % (@billing.without_tax + @billing.tax_price).to_i %></p>
      <p align="right"><%= '%.2f' % (@billing.amount - (@billing.without_tax + @billing.tax_price).to_i ) %></p>

    </div>
    <div class="col-md-1" style="background: powderblue">

    </div>
  </div>